all:
  children:
    win:
      hosts:
        test1:
          ansible_host: ip
          ansible_user: username
          ansible_password: pass
          ansible_port: 5985
          ansible_connection: winrm
          ansible_winrm_transport: ntlm
          ansible_winrm_server_cert_validation: ignore 
    astra-1.7:
      hosts:
        test1:
          ansible_host: ip
          ansible_user: username
          ansible_ssh_private_key_file: path/to/key
          ansible_become: yes
          ansible_become_method: sudo
          ansible_become_pass: pass for sudo
    ubuntu-20.04:
      hosts:
        test1:
          ansible_host: ip
          ansible_user: username
          ansible_ssh_private_key_file: path/to/key
          ansible_become: yes
          ansible_become_method: sudo
          ansible_become_pass: pass for sudo
    ubuntu-22.04:
      hosts:
        test1:
          ansible_host: ip
          ansible_user: username
          ansible_ssh_private_key_file: path/to/key
          ansible_become: yes
          ansible_become_method: sudo
          ansible_become_pass: pass for sudo
    ubuntu-24.04:
      hosts:
        test1:
          ansible_host: ip
          ansible_user: username
          ansible_ssh_private_key_file: path/to/key
          ansible_become: yes
          ansible_become_method: sudo
          ansible_become_pass: pass for sudo