---
- name: Gather OS version and print user name
  hosts: astra-1.7
  gather_facts: yes
  tasks:
    - name: Display OS version
      debug:
        msg: "The OS version is {{ ansible_distribution }} {{ ansible_distribution_version }}"
